name: GitHub Actions Demo
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *' # everyday at 6am
  push:
    branches:
      - '*'

jobs:
  Build-scipy-with-NumPy-Nightly-release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v2
      - run: docker build -t scipy-nightly-numpy scipy_w_nightly_numpy
      - run: docker tag scipy-nightly-numpy v0lantis/scipy-nightly-numpy
      - run: docker push v0lantis/scipy-nightly-numpy

  Build-scipy-with-NumPy-latest-commit:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v2
      - run: docker build -t scipy-latest-numpy-commit scipy_w_numpy_last_commit
      - run: docker tag scipy-latest-numpy-commit v0lantis/scipy-latest-numpy-commit
      - run: docker push v0lantis/scipy-latest-numpy-commit
